### ISSUE TITLE
Loading pubclic key also from secret resource

### ISSUE THREAD

**Issue by eumel8** [eumel8/cosignwebhook#12]
At the moment it's only possible to load the cosign public key as env var in Kubernetes deployment.
Additional use case would be to store this key in a secret and load it from them:

```
env:
- name: COSIGNPUBKEY
  valueFrom:
    secretKeyRef:
      key: cosign.pub
      name: cosign 
```
